### ISSUE TITLE
好奇shell里面那个MyApplication用Box.init也是赋值，怎么会调用到其他模块的Application。希望指点

### ISSUE THREAD

**Issue by janecer** [CysionLiu/KtDevBox#1]

**Comment by CysionLiu** [comment]
在主build.gradle文件里，添加了appjoint插件，这个插件使得项目构建时，在主application调用其生命周期方法时，动态的在对应的位置会调用@modulespec注解对应的方法，类似于反射+动态代理机制。具体代码请见appjoint这个库，里面有基于groovy语言的插件代码实现。

**Comment by janecer** [comment]
就是面向切面编程吧？我记得这个跟阿里百川sdk好像不兼容。阿里百川不允许你使用这方面库
